# Generated by Django 4.2.6 on 2023-11-21 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0004_category_movie_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
